### ISSUE TITLE
Very great work, wonder to have ade 100 tasks setting weight

### ISSUE THREAD

**Issue by QLYYLQ** [zhengyuan-xie/ECCV24_NeST#1]
hello, it is a very good work, do you have any ade 100 model weight which is trained at 100 class setting. We will cite your great work in our paper. Thanks you.

**Comment by zhengyuan-xie** [comment]
Thanks for your interest in our work. We have uploaded two checkpoints of ADE 100 [https://drive.google.com/drive/folders/1obQABbUEcyEceuIlel1yjIlnsTDdpqOI?usp=drive_link](https://drive.google.com/drive/folders/1obQABbUEcyEceuIlel1yjIlnsTDdpqOI?usp=drive_link) , you can try it.

**Comment by QLYYLQ** [comment]
Thanks a lot.
