### ISSUE TITLE
Great work! Ask for your weights

### ISSUE THREAD

**Issue by euyis1019** [zhengyuan-xie/ECCV24_NeST#2]
Hello, thanks for your great work, we don't have enough time to run all of your ade setting. would you please give me the ade 100-10 task settings weights with resnet101 backbone

**Comment by zhengyuan-xie** [comment]
Hi, as there are many settings/baselines/backbones in our paper, we only save checkpoints at the base step. Do you want MiB+NeST or PLOP+NeST? I can try to submit a job on the cluster to run it, but I'm not sure how long the wait will be, as CVPR ddl approaches.

**Comment by zhengyuan-xie** [comment]
@euyis1019 We have uploaded weights after the 100-10 final task (MiB+NeST & PLOP+NeST) on the Google Drive: [https://drive.google.com/drive/folders/1AWmYpfKyaYeR0lqr0MR9TQmIxdObul2m?usp=drive_link](https://drive.google.com/drive/folders/1AWmYpfKyaYeR0lqr0MR9TQmIxdObul2m?usp=drive_link). Hope this helps.

**Comment by euyis1019** [comment]
Thanks a lot!
